services:
  postgres_db:
    restart: always
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: banker_db
      POSTGRES_USER: owner
      POSTGRES_PASSWORD: localpasswd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-net

  app:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/banker_db
      SPRING_DATASOURCE_USERNAME: owner
      SPRING_DATASOURCE_PASSWORD: localpasswd
    ports:
      - 8080:8080
    networks:
      - app-net

networks:
  app-net:
volumes:
  postgres-data:
