spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/banker_db
    username: owner
    password: localpasswd
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  sql:
    init:
      mode: always