-- DROP TABLE IF EXISTS Persons;
-- DROP TABLE IF EXISTS Products;
-- DROP TABLE IF EXISTS Withdraws;

CREATE TABLE IF NOT EXISTS Persons(
      ID BIGSERIAL PRIMARY KEY,
      NAME VARCHAR(255) NOT NULL,
      EMAIL VARCHAR(100) NOT NULL,
      CONTACT VARCHAR(20),
      AGE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Products(
   ID BIGSERIAL PRIMARY KEY,
   PRODUCT_TYPE VARCHAR(255),
   NAME VARCHAR(255) NOT NULL,
   CURRENT_BALANCE BIGINT NOT NULL,
   EMAIL VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Withdraws(
    ID BIGSERIAL PRIMARY KEY,
    MESSAGE VARCHAR(255) NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_TYPE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    NEW_BALANCE BIGINT NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL
);